[package]
name = "tty"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
serenity = { version = "0.12.5", features = ["full"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
