[answer]
loading = "<a:loading:1400194849273282600>"
error   = "<a:error:1398985025688436797>"
yes     = "<a:yes:1398984778388340817>"
no      = "<a:no:1398984790337781770>"

[badge]
dev     = "<:dev:1398755085441564772>"
enium   = "<:enium_staff:1398755055930179586>"
buyer   = "<a:buyer:1398757139085922336>"
owner   = "<a:owner:1398757148078637167>"
pwn     = "<:pwn:1398755072317325403>"

[config]
enable  = "<:enable:1442500152471457965>"
disable = "<:disable:1442500007532953600>"
